# -*- coding: utf-8 -*-
"""week06_kiwu_iot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LSBUqBxX4L8a-EV0aESLXL0ffrLpz_dJ
"""

!pip --version

import numpy as np
import pandas as pd

l1 = [-17, "99", 2.9, 0, 55]
#a1 = np.array([-17, 99, 2, 0, 55]) #[-17, 99, 2, 0, 55]
a1 = np.array(l1)
a2 = np.ones(5, dtype=np.int64)
a3 = np.zeros(4, dtype=np.int64)
print(l1, type(l1))
print(a1, type(a1), a1.shape)
print(a2, type(a2), a2.shape)
print(a3, type(a3), a3.shape)

2025-10-15